#!/bin/sh
 
set -e
 
case "$1" in
  configure)
    ldconfig
   
  ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    echo "$1"
;;
  *)
    echo "postinst called with unknown argument \`\$1'" >&2
    exit 0
  ;;
esac
